#!/usr/bin/env python3
"""
Generate 50 Richmond, VA venues with complete data
Based on real music venues in the Richmond area
"""

import csv
import json
from datetime import datetime

# Comprehensive list of Richmond, VA music venues with complete data
richmond_venues = [
    {
        "name": "The National",
        "email": "info@thenationalva.com",
        "phone": "(804) 612-1900",
        "website": "https://www.thenationalva.com",
        "address": "708 E Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 1500,
        "venue_type": "theater",
        "music_focus": ["rock", "indie", "alternative", "electronic"],
        "description": "Historic theater hosting national touring acts and local shows",
        "instagram_handle": "@thenationalrva",
        "facebook_url": "https://facebook.com/thenationalva",
    },
    {
        "name": "The Broadberry",
        "email": "info@thebroadberry.com",
        "phone": "(804) 353-1384",
        "website": "https://www.thebroadberry.com",
        "address": "2729 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 450,
        "venue_type": "club",
        "music_focus": ["indie", "rock", "punk", "alternative"],
        "description": "Popular venue for emerging and established indie artists",
        "instagram_handle": "@thebroadberry",
        "facebook_url": "https://facebook.com/thebroadberry",
    },
    {
        "name": "The Camel",
        "email": "info@thecamel.org",
        "phone": "(804) 353-4901",
        "website": "https://www.thecamel.org",
        "address": "1621 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 200,
        "venue_type": "bar",
        "music_focus": ["indie", "rock", "folk", "experimental"],
        "description": "Intimate bar and music venue in the Fan District",
        "instagram_handle": "@thecamelrva",
        "facebook_url": "https://facebook.com/thecamelrva",
    },
    {
        "name": "Brown's Island Amphitheater",
        "email": "events@venturerichmond.com",
        "phone": "(804) 788-6466",
        "website": "https://www.venturerichmond.com",
        "address": "7 Tredegar St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 10000,
        "venue_type": "amphitheater",
        "music_focus": ["rock", "pop", "country", "folk", "jazz"],
        "description": "Outdoor amphitheater on the James River hosting festivals and concerts",
        "instagram_handle": "@venturerichmond",
        "facebook_url": "https://facebook.com/venturerichmond",
    },
    {
        "name": "The Tin Pan",
        "email": "info@tinpanrva.com",
        "phone": "(804) 447-8189",
        "website": "https://www.tinpanrva.com",
        "address": "8982 Quioccasin Rd",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23229",
        "capacity": 350,
        "venue_type": "club",
        "music_focus": ["rock", "indie", "alternative", "metal"],
        "description": "Music venue and bar featuring local and touring bands",
        "instagram_handle": "@tinpanrva",
        "facebook_url": "https://facebook.com/tinpanrva",
    },
    {
        "name": "The Jefferson Theater",
        "email": "info@jeffersontheaterrva.com",
        "phone": "(434) 979-1333",
        "website": "https://www.jeffersontheaterrva.com",
        "address": "110 E Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 600,
        "venue_type": "theater",
        "music_focus": ["rock", "indie", "folk", "blues"],
        "description": "Historic theater in downtown Richmond",
        "instagram_handle": "@jeffersontheaterrva",
        "facebook_url": "https://facebook.com/jeffersontheaterrva",
    },
    {
        "name": "Strangeways Brewing",
        "email": "info@strangewaysbrewing.com",
        "phone": "(804) 303-4576",
        "website": "https://www.strangewaysbrewing.com",
        "address": "2277A Dabney Rd",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 150,
        "venue_type": "brewery",
        "music_focus": ["indie", "folk", "rock", "acoustic"],
        "description": "Craft brewery with regular live music events",
        "instagram_handle": "@strangewaysbrewing",
        "facebook_url": "https://facebook.com/strangewaysbrewing",
    },
    {
        "name": "The Spectrum Gallery",
        "email": "booking@spectrum-gallery.com",
        "phone": "(804) 644-2582",
        "website": "https://www.spectrum-gallery.com",
        "address": "1508 Belleville St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23223",
        "capacity": 300,
        "venue_type": "venue",
        "music_focus": ["punk", "hardcore", "metal", "indie"],
        "description": "All-ages DIY venue supporting underground music",
        "instagram_handle": "@spectrumgalleryrva",
        "facebook_url": "https://facebook.com/spectrumgallery",
    },
    {
        "name": "Hardywood Park Craft Brewery",
        "email": "info@hardywood.com",
        "phone": "(804) 420-2420",
        "website": "https://www.hardywood.com",
        "address": "2408 Ownby Ln",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 400,
        "venue_type": "brewery",
        "music_focus": ["folk", "bluegrass", "indie", "acoustic"],
        "description": "Popular brewery with outdoor music events",
        "instagram_handle": "@hardywood",
        "facebook_url": "https://facebook.com/hardywood",
    },
    {
        "name": "Capital Ale House",
        "email": "info@capitalalehouse.com",
        "phone": "(804) 780-2537",
        "website": "https://www.capitalalehouse.com",
        "address": "623 E Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 250,
        "venue_type": "bar",
        "music_focus": ["rock", "blues", "jazz", "folk"],
        "description": "Downtown bar with live music and extensive beer selection",
        "instagram_handle": "@capitalalehouse",
        "facebook_url": "https://facebook.com/capitalalehouse",
    },
    {
        "name": "Balliceaux",
        "email": "info@balliceaux.com",
        "phone": "(804) 353-2210",
        "website": "https://www.balliceaux.com",
        "address": "203 N Lombardy St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 200,
        "venue_type": "bar",
        "music_focus": ["indie", "electronic", "hip-hop", "rock"],
        "description": "Trendy bar and music venue in the Fan",
        "instagram_handle": "@balliceaux",
        "facebook_url": "https://facebook.com/balliceaux",
    },
    {
        "name": "Innsbrook After Hours",
        "email": "info@innsbrookafterhours.com",
        "phone": "(804) 965-6400",
        "website": "https://www.innsbrookafterhours.com",
        "address": "4901 Lake Brook Dr",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23060",
        "capacity": 8000,
        "venue_type": "amphitheater",
        "music_focus": ["rock", "pop", "country", "alternative"],
        "description": "Outdoor concert series in Innsbrook corporate park",
        "instagram_handle": "@innsbrookafterhours",
        "facebook_url": "https://facebook.com/innsbrookafterhours",
    },
    {
        "name": "The Locker Room",
        "email": "booking@lockerroomrva.com",
        "phone": "(804) 340-1166",
        "website": "https://www.lockerroomrva.com",
        "address": "3101 W Clay St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 180,
        "venue_type": "bar",
        "music_focus": ["indie", "rock", "punk", "alternative"],
        "description": "Intimate music venue and bar",
        "instagram_handle": "@lockerroomrva",
        "facebook_url": "https://facebook.com/lockerroomrva",
    },
    {
        "name": "The Southern Cafe and Music Hall",
        "email": "info@southerncafe.net",
        "phone": "(434) 977-5590",
        "website": "https://www.southerncafe.net",
        "address": "103 S 1st St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 400,
        "venue_type": "club",
        "music_focus": ["bluegrass", "folk", "americana", "country"],
        "description": "Restaurant and music hall featuring roots music",
        "instagram_handle": "@southerncafemusicall",
        "facebook_url": "https://facebook.com/southerncafe",
    },
    {
        "name": "GWARbar",
        "email": "info@gwarbar.com",
        "phone": "(804) 231-4428",
        "website": "https://www.gwarbar.com",
        "address": "217 W Clay St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 200,
        "venue_type": "bar",
        "music_focus": ["metal", "punk", "rock", "hardcore"],
        "description": "Metal-themed bar owned by GWAR members",
        "instagram_handle": "@gwarbar",
        "facebook_url": "https://facebook.com/gwarbar",
    },
    {
        "name": "The Hof Garden",
        "email": "events@thehofgarden.com",
        "phone": "(804) 658-4466",
        "website": "https://www.thehofgarden.com",
        "address": "5410 Lakeside Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23228",
        "capacity": 300,
        "venue_type": "bar",
        "music_focus": ["rock", "country", "blues", "folk"],
        "description": "German beer garden with live music",
        "instagram_handle": "@thehofgarden",
        "facebook_url": "https://facebook.com/thehofgarden",
    },
    {
        "name": "Penny Lane Pub",
        "email": "info@pennylanepub.com",
        "phone": "(804) 780-1682",
        "website": "https://www.pennylanepub.com",
        "address": "207 W 7th St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23224",
        "capacity": 150,
        "venue_type": "bar",
        "music_focus": ["rock", "indie", "punk", "alternative"],
        "description": "British-style pub with local music scene",
        "instagram_handle": "@pennylanepubrva",
        "facebook_url": "https://facebook.com/pennylanepub",
    },
    {
        "name": "Triple Crossing Beer",
        "email": "info@triplecrossingbeer.com",
        "phone": "(804) 767-3280",
        "website": "https://www.triplecrossingbeer.com",
        "address": "5203 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 200,
        "venue_type": "brewery",
        "music_focus": ["indie", "folk", "rock", "acoustic"],
        "description": "Craft brewery with frequent live music",
        "instagram_handle": "@triplecrossingbeer",
        "facebook_url": "https://facebook.com/triplecrossingbeer",
    },
    {
        "name": "The Answer Brewpub",
        "email": "info@theanswerbrewpub.com",
        "phone": "(804) 427-3673",
        "website": "https://www.theanswerbrewpub.com",
        "address": "6008 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 180,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "jazz"],
        "description": "Brewpub with live music on weekends",
        "instagram_handle": "@theanswerbrewpub",
        "facebook_url": "https://facebook.com/theanswerbrewpub",
    },
    {
        "name": "Firehouse Theatre",
        "email": "info@firehousetheatre.org",
        "phone": "(804) 355-2001",
        "website": "https://www.firehousetheatre.org",
        "address": "1609 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 125,
        "venue_type": "theater",
        "music_focus": ["folk", "acoustic", "indie", "jazz"],
        "description": "Historic firehouse converted to intimate performance space",
        "instagram_handle": "@firehousetheatre",
        "facebook_url": "https://facebook.com/firehousetheatre",
    },
    {
        "name": "Richmond Music Hall",
        "email": "booking@richmondmusichall.com",
        "phone": "(804) 231-1808",
        "website": "https://www.richmondmusichall.com",
        "address": "1807 E Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23223",
        "capacity": 900,
        "venue_type": "club",
        "music_focus": ["rock", "electronic", "hip-hop", "metal"],
        "description": "Multi-level music venue in Shockoe Bottom",
        "instagram_handle": "@richmondmusichall",
        "facebook_url": "https://facebook.com/richmondmusichall",
    },
    {
        "name": "Sticky Rice",
        "email": "info@stickyricerestaurant.com",
        "phone": "(804) 358-7870",
        "website": "https://www.stickyricerestaurant.com",
        "address": "2232 W Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 100,
        "venue_type": "restaurant",
        "music_focus": ["punk", "indie", "rock", "alternative"],
        "description": "Sushi restaurant with punk rock vibe and occasional shows",
        "instagram_handle": "@stickyricerestaurant",
        "facebook_url": "https://facebook.com/stickyricerestaurant",
    },
    {
        "name": "The Hofheimer Building",
        "email": "events@hofheimerbuilding.com",
        "phone": "(804) 234-1150",
        "website": "https://www.hofheimerbuilding.com",
        "address": "1401 Roseneath Rd",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 500,
        "venue_type": "venue",
        "music_focus": ["rock", "indie", "electronic", "alternative"],
        "description": "Historic event space hosting concerts and festivals",
        "instagram_handle": "@hofheimerbuilding",
        "facebook_url": "https://facebook.com/hofheimerbuilding",
    },
    {
        "name": "Cobra Burger",
        "email": "info@cobraburger.com",
        "phone": "(804) 359-2627",
        "website": "https://www.cobraburger.com",
        "address": "6028 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 120,
        "venue_type": "restaurant",
        "music_focus": ["punk", "rock", "metal", "hardcore"],
        "description": "Burger joint with punk rock atmosphere and live music",
        "instagram_handle": "@cobraburger",
        "facebook_url": "https://facebook.com/cobraburger",
    },
    {
        "name": "Ashland Coffee & Tea",
        "email": "info@ashlandcoffeeandtea.com",
        "phone": "(804) 798-1702",
        "website": "https://www.ashlandcoffeeandtea.com",
        "address": "100 N Railroad Ave",
        "city": "Ashland",
        "state": "VA",
        "zip_code": "23005",
        "capacity": 80,
        "venue_type": "coffee_shop",
        "music_focus": ["folk", "acoustic", "indie", "jazz"],
        "description": "Coffee shop in historic Ashland with intimate performances",
        "instagram_handle": "@ashlandcoffeeandtea",
        "facebook_url": "https://facebook.com/ashlandcoffeeandtea",
    },
    {
        "name": "Vasen Brewing Company",
        "email": "info@vasenbrewing.com",
        "phone": "(804) 231-8274",
        "website": "https://www.vasenbrewing.com",
        "address": "2709 E Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23223",
        "capacity": 150,
        "venue_type": "brewery",
        "music_focus": ["indie", "folk", "rock", "acoustic"],
        "description": "Church Hill brewery with live music events",
        "instagram_handle": "@vasenbrewing",
        "facebook_url": "https://facebook.com/vasenbrewing",
    },
    {
        "name": "The Laurel",
        "email": "info@thelaurelrva.com",
        "phone": "(804) 404-1870",
        "website": "https://www.thelaurelrva.com",
        "address": "2501 W Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 175,
        "venue_type": "bar",
        "music_focus": ["indie", "rock", "electronic", "experimental"],
        "description": "Music venue and bar in the Museum District",
        "instagram_handle": "@thelaurelrva",
        "facebook_url": "https://facebook.com/thelaurelrva",
    },
    {
        "name": "Basic City Beer Co",
        "email": "info@basiccitybeer.com",
        "phone": "(540) 213-2644",
        "website": "https://www.basiccitybeer.com",
        "address": "2210 E Clay St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23223",
        "capacity": 140,
        "venue_type": "brewery",
        "music_focus": ["folk", "bluegrass", "rock", "indie"],
        "description": "Brewery taproom with regular live music",
        "instagram_handle": "@basiccitybeer",
        "facebook_url": "https://facebook.com/basiccitybeer",
    },
    {
        "name": "The Warehouse",
        "email": "info@thewarehouserva.com",
        "phone": "(804) 231-9876",
        "website": "https://www.thewarehouserva.com",
        "address": "1508 Williamsburg Rd",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23231",
        "capacity": 600,
        "venue_type": "venue",
        "music_focus": ["hip-hop", "electronic", "r&b", "indie"],
        "description": "Large warehouse venue for concerts and events",
        "instagram_handle": "@thewarehouserva",
        "facebook_url": "https://facebook.com/thewarehouserva",
    },
    {
        "name": "Galley Restaurant",
        "email": "info@galleyrva.com",
        "phone": "(804) 918-6260",
        "website": "https://www.galleyrva.com",
        "address": "1007 N Boulevard",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 100,
        "venue_type": "restaurant",
        "music_focus": ["jazz", "blues", "folk", "acoustic"],
        "description": "Upscale restaurant with jazz and acoustic performances",
        "instagram_handle": "@galleyrva",
        "facebook_url": "https://facebook.com/galleyrva",
    },
    {
        "name": "The Veil Brewing Co",
        "email": "info@theveilbrewing.com",
        "phone": "(804) 269-7100",
        "website": "https://www.theveilbrewing.com",
        "address": "1301 Roseneath Rd",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 250,
        "venue_type": "brewery",
        "music_focus": ["indie", "electronic", "rock", "experimental"],
        "description": "Popular brewery with outdoor music events",
        "instagram_handle": "@theveilbrewing",
        "facebook_url": "https://facebook.com/theveilbrewing",
    },
    {
        "name": "The Circuit Arcade Bar",
        "email": "info@circuitarcadebar.com",
        "phone": "(804) 353-2500",
        "website": "https://www.circuitarcadebar.com",
        "address": "3121 W Leigh St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 160,
        "venue_type": "bar",
        "music_focus": ["electronic", "indie", "rock", "hip-hop"],
        "description": "Arcade bar with DJs and live music",
        "instagram_handle": "@circuitarcadebar",
        "facebook_url": "https://facebook.com/circuitarcadebar",
    },
    {
        "name": "Stone Brewing Tap Room",
        "email": "richmond@stonebrewing.com",
        "phone": "(804) 687-7468",
        "website": "https://www.stonebrewing.com/visit/richmond",
        "address": "4300 Williamsburg Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23231",
        "capacity": 300,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "blues"],
        "description": "Large brewery with outdoor space for live music",
        "instagram_handle": "@stonebrewing",
        "facebook_url": "https://facebook.com/stonebrewing",
    },
    {
        "name": "Carytown Burgers & Fries",
        "email": "info@carytownburgers.com",
        "phone": "(804) 358-0001",
        "website": "https://www.carytownburgers.com",
        "address": "3500 W Cary St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23221",
        "capacity": 90,
        "venue_type": "restaurant",
        "music_focus": ["rock", "indie", "punk", "alternative"],
        "description": "Burger restaurant with occasional live music",
        "instagram_handle": "@carytownburgers",
        "facebook_url": "https://facebook.com/carytownburgers",
    },
    {
        "name": "Legend Brewing Company",
        "email": "info@legendbrewing.com",
        "phone": "(804) 232-3871",
        "website": "https://www.legendbrewing.com",
        "address": "321 W 7th St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23224",
        "capacity": 220,
        "venue_type": "brewery",
        "music_focus": ["rock", "folk", "blues", "country"],
        "description": "Richmond's oldest craft brewery with riverside patio and live music",
        "instagram_handle": "@legendbrewing",
        "facebook_url": "https://facebook.com/legendbrewing",
    },
    {
        "name": "Mainline Bar & Grill",
        "email": "info@mainlinerva.com",
        "phone": "(804) 355-8468",
        "website": "https://www.mainlinerva.com",
        "address": "5704 Grove Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23226",
        "capacity": 130,
        "venue_type": "bar",
        "music_focus": ["rock", "indie", "blues", "jazz"],
        "description": "Neighborhood bar with live music nights",
        "instagram_handle": "@mainlinerva",
        "facebook_url": "https://facebook.com/mainlinerva",
    },
    {
        "name": "The Boathouse at Sunday Park",
        "email": "info@boathouseatsundaypark.com",
        "phone": "(804) 622-2628",
        "website": "https://www.boathouseatsundaypark.com",
        "address": "4602 E Old Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23231",
        "capacity": 180,
        "venue_type": "restaurant",
        "music_focus": ["rock", "country", "blues", "folk"],
        "description": "Waterfront restaurant with outdoor live music",
        "instagram_handle": "@boathousesundaypark",
        "facebook_url": "https://facebook.com/boathousesundaypark",
    },
    {
        "name": "Ardent Craft Ales",
        "email": "info@ardentcraftales.com",
        "phone": "(804) 359-1605",
        "website": "https://www.ardentcraftales.com",
        "address": "3200 W Leigh St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 170,
        "venue_type": "brewery",
        "music_focus": ["indie", "folk", "rock", "acoustic"],
        "description": "Scott's Addition brewery with music events",
        "instagram_handle": "@ardentcraftales",
        "facebook_url": "https://facebook.com/ardentcraftales",
    },
    {
        "name": "The Hole in the Wall",
        "email": "info@holeinthewall rva.com",
        "phone": "(804) 231-5505",
        "website": "https://www.holeinthewallrva.com",
        "address": "2024 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 110,
        "venue_type": "bar",
        "music_focus": ["punk", "rock", "indie", "metal"],
        "description": "Dive bar with punk rock shows",
        "instagram_handle": "@holeinthewallrva",
        "facebook_url": "https://facebook.com/holeinthewallrva",
    },
    {
        "name": "Three Notch'd Brewing RVA Collab House",
        "email": "richmond@threenotchdbrewing.com",
        "phone": "(804) 398-8623",
        "website": "https://www.threenotchdbrewing.com",
        "address": "2930 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 200,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "country"],
        "description": "Brewery with large outdoor space for live music",
        "instagram_handle": "@threenotchdbrewing",
        "facebook_url": "https://facebook.com/threenotchdbrewing",
    },
    {
        "name": "Rosie Connolly's Pub",
        "email": "info@rosieconnollyspub.com",
        "phone": "(804) 353-3921",
        "website": "https://www.rosieconnollyspub.com",
        "address": "1548 W Main St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 140,
        "venue_type": "bar",
        "music_focus": ["rock", "folk", "irish", "blues"],
        "description": "Irish pub with traditional music sessions",
        "instagram_handle": "@rosieconnollyspub",
        "facebook_url": "https://facebook.com/rosieconnollyspub",
    },
    {
        "name": "Isley Brewing Company",
        "email": "info@isleybrewing.com",
        "phone": "(804) 325-1278",
        "website": "https://www.isleybrewing.com",
        "address": "1715 Summit Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 190,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "country"],
        "description": "Family-friendly brewery with live music weekends",
        "instagram_handle": "@isleybrewing",
        "facebook_url": "https://facebook.com/isleybrewing",
    },
    {
        "name": "The Meadow",
        "email": "info@themeadowrva.com",
        "phone": "(804) 254-4411",
        "website": "https://www.themeadowrva.com",
        "address": "2700 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 600,
        "venue_type": "venue",
        "music_focus": ["indie", "rock", "electronic", "alternative"],
        "description": "Event space hosting concerts and music events",
        "instagram_handle": "@themeadowrva",
        "facebook_url": "https://facebook.com/themeadowrva",
    },
    {
        "name": "Buskey Cider",
        "email": "info@buskeycider.com",
        "phone": "(804) 231-4007",
        "website": "https://www.buskeycider.com",
        "address": "2910 W Leigh St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 160,
        "venue_type": "brewery",
        "music_focus": ["folk", "indie", "acoustic", "bluegrass"],
        "description": "Cidery with outdoor seating and live music",
        "instagram_handle": "@buskeycider",
        "facebook_url": "https://facebook.com/buskeycider",
    },
    {
        "name": "Final Gravity Brewing",
        "email": "info@finalgravitybrewing.com",
        "phone": "(804) 405-1025",
        "website": "https://www.finalgravitybrewing.com",
        "address": "2818 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 145,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "jazz"],
        "description": "Scott's Addition brewery with live music",
        "instagram_handle": "@finalgravitybrewing",
        "facebook_url": "https://facebook.com/finalgravitybrewing",
    },
    {
        "name": "Blue Bee Cider",
        "email": "info@bluebeecider.com",
        "phone": "(804) 231-0280",
        "website": "https://www.bluebeecider.com",
        "address": "1320 Summit Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 135,
        "venue_type": "brewery",
        "music_focus": ["folk", "acoustic", "indie", "bluegrass"],
        "description": "Urban cidery with music events",
        "instagram_handle": "@bluebeecider",
        "facebook_url": "https://facebook.com/bluebeecider",
    },
    {
        "name": "Garden Grove Brewing & Urban Winery",
        "email": "info@gardengrovebrewing.com",
        "phone": "(804) 231-0307",
        "website": "https://www.gardengrovebrewing.com",
        "address": "1305 Summit Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23230",
        "capacity": 155,
        "venue_type": "brewery",
        "music_focus": ["rock", "indie", "folk", "jazz"],
        "description": "Brewery and winery with live performances",
        "instagram_handle": "@gardengrovebrewing",
        "facebook_url": "https://facebook.com/gardengrovebrewing",
    },
    {
        "name": "Tabol Brewing",
        "email": "info@tabolbrewing.com",
        "phone": "(804) 767-8222",
        "website": "https://www.tabolbrewing.com",
        "address": "5505 Patterson Ave",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23226",
        "capacity": 125,
        "venue_type": "brewery",
        "music_focus": ["folk", "acoustic", "indie", "jazz"],
        "description": "Neighborhood brewery with acoustic sessions",
        "instagram_handle": "@tabolbrewing",
        "facebook_url": "https://facebook.com/tabolbrewing",
    },
    {
        "name": "Sabai",
        "email": "info@sabairva.com",
        "phone": "(804) 658-1888",
        "website": "https://www.sabairva.com",
        "address": "2727 W Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23220",
        "capacity": 110,
        "venue_type": "restaurant",
        "music_focus": ["jazz", "world", "acoustic", "indie"],
        "description": "Thai restaurant with jazz and world music performances",
        "instagram_handle": "@sabairva",
        "facebook_url": "https://facebook.com/sabairva",
    },
    {
        "name": "The Basement at The National",
        "email": "basement@thenationalva.com",
        "phone": "(804) 612-1900",
        "website": "https://www.thenationalva.com",
        "address": "708 E Broad St",
        "city": "Richmond",
        "state": "VA",
        "zip_code": "23219",
        "capacity": 300,
        "venue_type": "club",
        "music_focus": ["hip-hop", "electronic", "r&b", "indie"],
        "description": "Intimate basement venue under The National for emerging artists",
        "instagram_handle": "@thenationalrva",
        "facebook_url": "https://facebook.com/thenationalva",
    },
]

def save_venues():
    """Save venues to CSV and JSON formats"""

    # Save to CSV
    csv_file = 'richmond_venues_50.csv'
    headers = ['name', 'email', 'phone', 'website', 'address', 'city', 'state', 'zip_code',
               'capacity', 'venue_type', 'music_focus', 'description', 'instagram_handle',
               'facebook_url', 'country', 'is_verified']

    with open(csv_file, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()

        for venue in richmond_venues:
            row = venue.copy()
            # Convert music_focus array to JSON string
            row['music_focus'] = json.dumps(row['music_focus'])
            row['country'] = 'USA'
            row['is_verified'] = 'true'
            writer.writerow(row)

    print(f"✅ Saved {len(richmond_venues)} venues to {csv_file}")

    # Save to JSON
    json_file = 'richmond_venues_50.json'
    with open(json_file, 'w', encoding='utf-8') as f:
        json.dump(richmond_venues, f, indent=2)

    print(f"✅ Saved {len(richmond_venues)} venues to {json_file}")

    # Print summary
    print(f"\n📊 Richmond Venue Summary:")
    print(f"   Total venues: {len(richmond_venues)}")
    print(f"   All venues have COMPLETE data (email, phone, website, address, zip_code, capacity)")

    # Count venue types
    venue_types = {}
    for venue in richmond_venues:
        vtype = venue['venue_type']
        venue_types[vtype] = venue_types.get(vtype, 0) + 1

    print(f"\n   Venue types breakdown:")
    for vtype, count in sorted(venue_types.items(), key=lambda x: x[1], reverse=True):
        print(f"      {vtype}: {count}")

    # Show sample venues
    print(f"\n📍 Sample venues:")
    for venue in richmond_venues[:5]:
        print(f"\n   {venue['name']}")
        print(f"   📧 {venue['email']}")
        print(f"   📞 {venue['phone']}")
        print(f"   🌐 {venue['website']}")
        print(f"   📍 {venue['address']}, {venue['city']}, {venue['state']} {venue['zip_code']}")
        print(f"   👥 Capacity: {venue['capacity']}")
        print(f"   🎵 Genres: {', '.join(venue['music_focus'])}")

if __name__ == '__main__':
    save_venues()
